<div style="background-color:lightblue; padding:40px; text-align:center; border-radius:10px;">

  <h1 style="color:#333; font-size:3em; margin-bottom:20px;">A LOOK INTO NUMPY FROM A-Z </h1>

  <p style="font-size:1.5em; color:#666;">Diving deep into python numpy library</p>

</div>

## <h1 style="color:pink;">A BRIEF SUMMARY OF NUMPY COMMANDS </h1>

### **start by running: import numpy as np**

*   **` In order for you to see the capabilities of a particular command, just pick the command and add ? or ?? to the end of the command then run that cell:`**

### **Array Creation Functions**
*   **`np.array()`**: The most common way to create an **ndarray** from a sequence-like object, such as a list or tuple.
*   **`np.zeros()`** and **`np.ones()`**: Create arrays filled with zeros or ones, respectively, for a specified shape.
*   **`np.empty()`**: Allocates memory for an array without initializing its values to a particular number.
*   **`np.arange()`**: Returns an array containing a numerical sequence based on specified start, end, and step rules.
*   **`np.linspace()`**: Creates a sequence of evenly spaced numbers over a specified interval.
*   **`np.full()`**: Produces an array of a given shape where every element is set to a specific "fill value".
*   **`np.eye()`** or **`np.identity()`**: Generates a square N x N identity matrix.
*   **`np.asarray()`**: Converts input data to an ndarray but avoids copying the data if the input is already an ndarray.

### **Array Manipulation and Shape Modification**
*   **`.reshape()`**: Changes the dimensions of an array without altering its data.
*   **`.ravel()`**: Flattens a multidimensional array into a one-dimensional array, returning a view if possible.
*   **`.flatten()`**: Similar to `ravel`, but always returns a **copy** of the data.
*   **`.transpose()`** or **`.T`**: Transposes the array (swaps rows and columns).
*   **`.swapaxes()`**: Switches a pair of axis numbers to rearrange the data.
*   **`np.concatenate()`**: Joins a sequence of arrays along an existing axis.
*   **`np.vstack()`** / **`np.row_stack()`**: Stacks arrays vertically (along rows).
*   **`np.hstack()`**: Stacks arrays horizontally (along columns).
*   **`np.column_stack()`**: Stacks 1D arrays as columns into a 2D array.
*   **`np.split()`**: Divides an array into multiple smaller arrays along a specified axis.
*   **`np.hsplit()`** / **`np.vsplit()`**: Convenience functions for splitting arrays horizontally or vertically.
*   **`np.tile()`**: Replicates an array by "tiling" it a specified number of times along given axes.
*   **`.repeat()`**: Replicates each individual element in an array a specified number of times.

### **Indexing, Selection, and Logic**
*   **`np.where()`**: A vectorized version of the ternary expression `x if condition else y`.
*   **`.take()`**: Retrieves elements from an array along a single axis using an integer index array.
*   **`.put()`**: Sets values in an array at specified indices (indexes into the flattened version).
*   **`np.newaxis`**: A special attribute used to insert a new axis of length 1, often for **broadcasting** purposes.
*   **`np.issubdtype()`**: Checks if a particular dtype is a subclass of another in the NumPy type hierarchy.

### **Mathematical and Universal Functions (ufuncs)**
*   **`np.sqrt()`**: Computes the element-wise square root.
*   **`np.exp()`**: Computes the element-wise exponential ($e^x$).
*   **`np.log()`**, **`np.log10()`**, **`np.log2()`**: Natural and base-10/base-2 logarithms.
*   **`np.sin()`**, **`np.cos()`**, **`np.tan()`**: Basic trigonometric functions.
*   **`np.abs()`** or **`np.fabs()`**: Computes the absolute value element-wise.
*   **`np.maximum()`** and **`np.minimum()`**: Element-wise maximum or minimum of two arrays.
*   **`np.sign()`**: Returns 1 for positive, -1 for negative, and 0 for zero values.
*   **`np.ceil()`** and **`np.floor()`**: Ceiling and floor operations.
*   **`np.modf()`**: Returns the fractional and integral parts of a floating-point array as separate arrays.
*   **`np.logical_and()`**, **`np.logical_or()`**, **`np.logical_xor()`**: Performs element-wise Boolean operations.

### **Statistical Methods and Aggregations**
*   **`.sum()`**: Computes the sum of all elements or along a specific axis.
*   **`.mean()`**: Computes the arithmetic mean.
*   **`.std()`** and **`.var()`**: Compute standard deviation and variance.
*   **`.min()`** and **`.max()`**: Find the minimum and maximum values.
*   **`.argmin()`** and **`.argmax()`**: Find the indices of the minimum and maximum elements.
*   **`.cumsum()`** and **`.cumprod()`**: Compute the cumulative sum or product.
*   **`.any()`** and **`.all()`**: Test whether any or all elements evaluate to `True`.

### **Sorting and Set Logic**
*   **`.sort()`**: Rearranges an array in place.
*   **`np.sort()`**: Returns a sorted **copy** of an array.
*   **`.argsort()`**: Returns the integer indices that would sort an array.
*   **`np.lexsort()`**: Performs an indirect lexicographical sort on multiple key arrays.
*   **`np.unique()`**: Finds the sorted unique elements in an array.
*   **`np.in1d()`**: Tests membership of values from one array in another.
*   **`np.partition()`** and **`np.argpartition()`**: Partition an array around the k-th smallest element.
*   **`.searchsorted()`**: Performs a binary search on a sorted array to find insertion points.

### **Linear Algebra (`np.linalg`)**
*   **`np.dot()`**: Performs matrix multiplication.
*   **`@` operator**: Shorthand for matrix multiplication.
*   **`inv()`**: Computes the inverse of a square matrix.
*   **`qr()`**: Computes the QR decomposition.
*   **`det()`**, **`eig()`**, **`svd()`**: Compute determinant, eigenvalues/eigenvectors, and singular value decomposition.

### **Random Number Generation (`np.random`)**
*   **`rng.standard_normal()`**: Draws samples from a standard normal distribution.
*   **`rng.integers()`**: Generates random integers over a specified range.
*   **`rng.permutation()`**: Returns a random permutation of a sequence or range.
*   **`rng.uniform()`**: Draws samples from a uniform distribution.
*   **`np.random.seed()`**: Sets the seed for reproducibility.

### **File Input and Output**
*   **`np.save()`** and **`np.load()`**: Efficiently save and load single arrays in binary **.npy** format.
*   **`np.savez()`** and **`np.savez_compressed()`**: Save multiple arrays into an uncompressed or compressed **.npz** archive.
*   **`np.genfromtxt()`**: Loads data from a text file into an array, handling delimiters and headers.
*   **`np.fromfile()`**: Reads data from a binary file into an array (often used for structured data).

### **Advanced Utilities**
*   **`np.memmap()`**: Allows for interacting with very large binary data on disk as if it were an in-memory array.
*   **`np.frompyfunc()`** and **`np.vectorize()`**: Tools for creating custom ufunc-like functions from pure Python functions.
*   **`np.meshgrid()`**: Creates coordinate matrices from coordinate vectors.
*   **`np.digitize()`**: Returns the indices of the bins to which each value in an input array belongs.
*   **`.astype()`**: Explicitly casts an array from one data type to another.

In [1]:
import numpy as np

In [2]:
# Creating a 5x4 matrix with random integers between 10 and 100
np.random.seed(42)  # For reproducibility
data = np.random.randint(10, 100, size=(5, 4))

print("Sample Dataset:\n", data)


Sample Dataset:
 [[61 24 81 70]
 [30 92 96 84]
 [84 97 33 12]
 [31 62 11 97]
 [39 47 11 73]]


## <span style="color:pink;"><u><h4>dataset dimensions</h4></u></span>

In [3]:
print("Shape of dataset:", data.shape)  # (rows, columns)
print("Size of dataset:", data.size)    # Total number of elements
print("Number of dimensions:", data.ndim)  # Number of dimensions

Shape of dataset: (5, 4)
Size of dataset: 20
Number of dimensions: 2


In [4]:
data.shape

(5, 4)

## <span style="color:pink;"><u><h3>SIMPLE OPERATIONS</h3></u></span>
## <span style="color:orange;"><u><h4>add, subtract, multiply, division, modulus, floor division, sum, power</4></u></span>

In [5]:
print("After Addition:\n", data + 5)

After Addition:
 [[ 66  29  86  75]
 [ 35  97 101  89]
 [ 89 102  38  17]
 [ 36  67  16 102]
 [ 44  52  16  78]]


In [6]:
print("After Subtraction:\n", data - 3)

After Subtraction:
 [[58 21 78 67]
 [27 89 93 81]
 [81 94 30  9]
 [28 59  8 94]
 [36 44  8 70]]


In [26]:
print("After Multiplication:\n", data * 2)

After Multiplication:
 [[122  48 162 140]
 [ 60 184 192 168]
 [168 194  66  24]
 [ 62 124  22 194]
 [ 78  94  22 146]]


In [28]:
print("After Division:\n", data / 4)

After Division:
 [[15.25  6.   20.25 17.5 ]
 [ 7.5  23.   24.   21.  ]
 [21.   24.25  8.25  3.  ]
 [ 7.75 15.5   2.75 24.25]
 [ 9.75 11.75  2.75 18.25]]


In [30]:
#floor division (eg 24/4 the multiple of 4 used is 6 the 6 is the value for the floor division 
print("After Floor Division:\n", data // 4)

After Floor Division:
 [[15  6 20 17]
 [ 7 23 24 21]
 [21 24  8  3]
 [ 7 15  2 24]
 [ 9 11  2 18]]


In [32]:
#modulus (eg 61/4 the rem is 1 hence 1 is the modulus
print("After Modulus:\n", data % 4)

After Modulus:
 [[1 0 1 2]
 [2 0 0 0]
 [0 1 1 0]
 [3 2 3 1]
 [3 3 3 1]]


In [34]:
#exponentiality or power multiplies the value by itself eg 24*24 is same as 24**2
print("After Power:\n", data ** 2)

After Power:
 [[3721  576 6561 4900]
 [ 900 8464 9216 7056]
 [7056 9409 1089  144]
 [ 961 3844  121 9409]
 [1521 2209  121 5329]]


In [50]:
Sum_of_all_elements=np.sum(data)
print("sum of the elements in the arrayS is:", Sum_of_all_elements)

sum of the elements in the arrayS is: 1135


In [54]:
Sum_of_each_column=np.sum(data, axis=0) # Column-wise sum
Sum_of_each_row=np.sum(data, axis=1)# Row-wise sum
print("Sum of each column:", Sum_of_each_column)
print("Sum of each row:", Sum_of_each_row)

Sum of each column: [245 322 232 336]
Sum of each row: [236 302 226 201 170]


## <span style="color:pink;"><u><h4>mean, median, std, variance, min and max</h4></u></span>

In [56]:
a=np.mean(data)
a

56.75

In [62]:
b=np.median(data)
b

61.5

In [64]:
print("Standard Deviation:", np.std(data))

Standard Deviation: 30.162683899149293


In [66]:
print("Variance:", np.var(data))

Variance: 909.7875


In [72]:
c=np.min(data)
c

11

In [76]:
d=np.max(data)
d

97

In [78]:
#min in each column and the max of each row
print("Minimum in each column:", np.min(data, axis=0))
print("Maximum in each row:", np.max(data, axis=1))

Minimum in each column: [30 24 11 12]
Maximum in each row: [81 96 97 97 73]


In [80]:
#max of each column and the min of each row
print("maximum in each column:", np.max(data, axis=0))
print("Minimum in each row:", np.min(data, axis=1))

maximum in each column: [84 97 96 97]
Minimum in each row: [24 30 12 11 11]


## <span style="color:pink;"><u><h3>logical operators</h3></u></span>

In [82]:
print("Elements greater than 50:\n", data > 50)

Elements greater than 50:
 [[ True False  True  True]
 [False  True  True  True]
 [ True  True False False]
 [False  True False  True]
 [False False False  True]]


In [87]:
e=data < 25
print("Elements below 25:\n", e)

Elements below 25:
 [[False  True False False]
 [False False False False]
 [False False False  True]
 [False False  True False]
 [False False  True False]]


## <span style="color:pink;"><u><h3>indexing and slicing</h3></u></span>

In [100]:
#remember in python indexing starts at 0
p=data[2, 3]
print("Element at row 2, column 3:", p)

Element at row 2, column 3: 12


In [102]:
print("Sliced Submatrix:\n", data[1:4, 0:3])

Sliced Submatrix:
 [[30 92 96]
 [84 97 33]
 [31 62 11]]


## <span style="color:pink;"><u><h3>reshaping a matrix and transposing</h3></u></span>

In [104]:
reshaped_data = data.reshape(10, 2)
print("Reshaped Dataset (10x2):\n", reshaped_data)

Reshaped Dataset (10x2):
 [[61 24]
 [81 70]
 [30 92]
 [96 84]
 [84 97]
 [33 12]
 [31 62]
 [11 97]
 [39 47]
 [11 73]]


In [107]:
print("Transpose of Dataset:\n", data.T)

Transpose of Dataset:
 [[61 30 84 31 39]
 [24 92 97 62 47]
 [81 96 33 11 11]
 [70 84 12 97 73]]


## <span style="color:pink;"><u><h3>sorting</h3></u></span>

In [110]:
print("Row-wise Sorted:\n", np.sort(data, axis=1))

Row-wise Sorted:
 [[24 61 70 81]
 [30 84 92 96]
 [12 33 84 97]
 [11 31 62 97]
 [11 39 47 73]]


In [112]:
print("Column-wise Sorted:\n", np.sort(data, axis=0))

Column-wise Sorted:
 [[30 24 11 12]
 [31 47 11 70]
 [39 62 33 73]
 [61 92 81 84]
 [84 97 96 97]]


## <span style="color:pink;"><u><h3>unique elements</h3></u></span>

In [116]:
print("Unique Elements:", np.unique(data))

Unique Elements: [11 12 24 30 31 33 39 47 61 62 70 73 81 84 92 96 97]


## <span style="color:pink;"><u><h3>matrix operations</h3></u></span>

In [121]:
B = np.random.randint(10, 100, size=(4, 4))  # Creating another 4x4 matrix
print("Matrix B:\n", B)

dot_product = np.dot(data[:, :4], B)  # Multiplying data (5x4) with B (4x4)
print("Dot Product Result:\n", dot_product)

Matrix B:
 [[69 30 42 85]
 [67 31 98 58]
 [68 51 69 89]
 [24 71 71 56]]
Dot Product Result:
 [[13005 11675 15473 17706]
 [16778 14612 22864 21134]
 [14827  8062 16163 16375]
 [ 9369 10300 15024 12642]
 [ 8340  8371 12186 11108]]
